data:
  problem_id: 19
  domain:
  - 0.0
  - 1.0
  num_quadrature_nodes: 10
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 128
  num_boundary_points_lbfgs: 2
  num_quadrature_points: 10
model:
  output_dim: 2
  type: RISN
  num_blocks: 3
  activation: Tanh
  hidden_features: 128
experiment:
  seed: 42
  name: RISN_prob19
  best_mae: 2.6020155928563327e-05
training:
  optimizer: Hybrid
  learning_rate: 0.0015250987829768788
  learning_rate_lbfgs: 1.0
  scheduler: WarmupCosine
  warmup_epochs: 5
  epochs: 4000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
  weight_decay: 2.4800522413468638e-05
