data:
  problem_id: 34
  domain:
  - - 0.0
    - 1.0
  - - 0.0
    - 1.0
  num_quadrature_nodes: 5
  num_collocation_points_adam: 500
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 128
  num_boundary_points_lbfgs: 64
  num_quadrature_points: 5
experiment:
  seed: 42
  name: RISN_prob34
  best_mae: 9.285692067351192e-05
model:
  type: RISN
  num_blocks: 2
  activation: Tanh
  hidden_features: 64
  output_dim: 1
training:
  optimizer: Hybrid
  learning_rate: 0.0004981087962616954
  learning_rate_lbfgs: 1.0
  scheduler: WarmupCosine
  warmup_epochs: 105
  epochs: 4000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
  weight_decay: 3.1520956154130396e-05
