data:
  problem_id: 6
  domain:
  - 0.0
  - 1.0
  num_quadrature_nodes: 10
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 32
  num_boundary_points_lbfgs: 64
experiment:
  seed: 42
  name: MLP_prob6
  best_mae: 0.003799293888732791
model:
  type: MLP
  hidden_layers: 1
  activation: Tanh
  hidden_features: 64
training:
  learning_rate: 0.003841235364387922
  optimizer: AdamW
  scheduler: WarmupCosine
  warmup_epochs: 144
  epochs: 4000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
  weight_decay: 3.041079148963289e-06
