data:
  problem_id: 6
  domain:
  - 0.0
  - 1.0
  num_quadrature_nodes: 10
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 64
  num_boundary_points_lbfgs: 64
experiment:
  seed: 42
  name: RISN_prob6
  best_mae: 0.0019941276405006647
model:
  type: RISN
  num_blocks: 4
  activation: Tanh
  hidden_features: 128
training:
  learning_rate: 0.0023093412121738257
  optimizer: AdamW
  scheduler: WarmupCosine
  warmup_epochs: 370
  epochs: 4000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
  weight_decay: 1.0357741801820807e-05
