data:
  problem_id: 25
  num_quadrature_nodes: 10
  domain:
  - 0.0
  - 1.0
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 64
  num_boundary_points_lbfgs: 64
  num_quadrature_points: 10
experiment:
  seed: 42
  name: RISN_prob25
  best_mae: 4.317208549764473e-06
model:
  type: RISN
  num_blocks: 3
  activation: Tanh
  hidden_features: 32
  output_dim: 1
training:
  optimizer: Hybrid
  learning_rate: 0.0018502397202950682
  learning_rate_lbfgs: 1.0
  scheduler: WarmupCosine
  warmup_epochs: 485
  epochs: 10000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
  weight_decay: 1.3325537920194702e-06
