model:
  activation: GELU
  hidden_features: 64
  num_decoder_layers: 2
  num_heads: 8
  num_support_points: 64
  support_points_distribution: grid
  beta_penalty: 5.0
  causal_mask: false
  use_rff: false
  rff_sigma: 1.0
  type: TLP
training:
  optimizer: AdamW
  learning_rate: 0.0004795289942491372
  weight_decay: 2.1296439129130947e-06
  scheduler: WarmupCosine
  warmup_epochs: 132
  warm_start_unfreeze_epoch: 2000
  epochs: 4000
  early_stopping_patience: 500
  early_stopping_min_delta: 1.0e-05
data:
  num_quadrature_nodes: 10
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 2000
  num_boundary_points_adam: 31
  num_boundary_points_lbfgs: 64
  domain:
  - 0.0
  - 1.0
  problem_id: 22
experiment:
  seed: 42
  name: prob22_tlp
  best_mae: 0.06480531394481659
