data:
  problem_id: 8
  domain:
  - - 0.0
    - 1.0
  - - 0.0
    - 2.0
  num_quadrature_nodes: 5
  num_collocation_points_adam: 500
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 64
  num_boundary_points_lbfgs: 64
  num_quadrature_points: 5
experiment:
  seed: 42
  name: TLP_posEnc_GlobalSkip_prob8
  best_mae: 0.005321567878127098
model:
  type: TLP
  pos_encoder: true
  pos_encoder_type: lff
  learn_mem_val: true
  global_skip: true
  skip_use_pretrained_mlp: true
  skip_mlp_trainable: true
  activation: Tanh
  hidden_features: 128
  num_heads: 2
  num_decoder_layers: 1
  LinNorm: true
  residual_norm: false
  num_support_points: 64
  support_points_distribution: grid
  beta_penalty: 5.0
  causal_mask: false
  siren_omega: 28.875367935467548
  output_dim: 1
training:
  warm_start: false
  warm_start_unfreeze_epoch: 3000
  warm_start_study_name: null
  early_stopping_patience: 2500
  learning_rate: 0.001175746367804369
  weight_decay: 9.020541257103417e-06
  optimizer: AdamW
  scheduler: WarmupCosine
  warmup_epochs: 46
  epochs: 4000
  early_stopping_min_delta: 1.0e-05
