data:
  problem_id: 24
  num_quadrature_nodes: 10
  domain:
  - 0.0
  - 1.0
  num_collocation_points_adam: 250
  num_collocation_points_lbfgs: 500
  num_boundary_points_adam: 32
  num_boundary_points_lbfgs: 64
  num_quadrature_points: 10
experiment:
  seed: 42
  name: TLP_residualNorm_true_prob24
  best_mae: 4.936134791933e-05
model:
  type: TLP
  pos_encoder: true
  pos_encoder_type: lff
  learn_mem_val: false
  global_skip: true
  skip_use_pretrained_mlp: false
  skip_mlp_trainable: false
  activation: GELU
  hidden_features: 64
  num_heads: 8
  num_decoder_layers: 4
  LinNorm: false
  residual_norm: true
  num_support_points: 128
  support_points_distribution: grid
  beta_penalty: 5.0
  causal_mask: false
  siren_omega: 19.869175464213708
  output_dim: 1
training:
  warm_start: false
  warm_start_unfreeze_epoch: 2000
  warm_start_study_name: null
  early_stopping_patience: 2500
  learning_rate: 0.005367782436173
  weight_decay: 1.0820347955386093e-06
  optimizer: AdamW
  scheduler: WarmupCosine
  warmup_epochs: 999
  epochs: 10000
  early_stopping_min_delta: 1.0e-05
